twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
